name: android release v1
on: workflow_dispatch

jobs:
  build:
    name: android release v1
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - id: read-version
          uses: NiklasLehnfeld/flutter-version-number-action@main
          with:
            file-path: pubspec.yaml
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.10.5'
        - name: Install project dependencies
          run: flutter pub get
        - name: Build artifacts
          run: flutter build apk --release
        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            type: 'zip'
            filename: PartTracker-${{github.ref_name}}-${{steps.read-version.outputs.version-number}}.zip
            directory: build/app/outputs
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: PartTracker-win-${{steps.read-version.outputs.version-number}}
            files: build/app/outputs/PartTracker-${{github.ref_name}}-windows-${{steps.read-version.outputs.version-number}}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
